package com.google.android.gms.internal.ads;

import android.content.Context;
import androidx.exifinterface.media.ExifInterface;
import androidx.lifecycle.CoroutineLiveDataKt;
import androidx.recyclerview.widget.ItemTouchHelper;
import androidx.vectordrawable.graphics.drawable.PathInterpolatorCompat;
import androidx.work.PeriodicWorkRequest;
import coil3.disk.DiskLruCache;
import com.google.firebase.messaging.ServiceStarter;
import java.util.concurrent.TimeUnit;
import okhttp3.HttpUrl;

/* compiled from: com.google.android.gms:play-services-ads-lite@@23.5.0 */
public final class zzbcn {
    public static final zzbce zzA = zzbce.zzg(1, "gads:preload_rewarded_queue_size:upper_bound", 15, 15);
    public static final zzbce zzB = zzbce.zzg(1, "gads:preload_app_open_default_buffer_size", 1, 1);
    public static final zzbce zzC = zzbce.zzg(1, "gads:preload_interstitial_default_buffer_size", 1, 1);
    public static final zzbce zzD = zzbce.zzg(1, "gads:preload_rewarded_default_buffer_size", 1, 1);
    public static final zzbce zzE = zzbce.zzg(1, "gads:preload_app_open_buffer_size:lower_bound", 1, 1);
    public static final zzbce zzF = zzbce.zzg(1, "gads:preload_interstitial_buffer_size:lower_bound", 1, 1);
    public static final zzbce zzG = zzbce.zzg(1, "gads:preload_rewarded_buffer_size:lower_bound", 1, 1);
    public static final zzbce zzH = zzbce.zzh(1, "gads:video_stream_cache:limit_time_sec", 300, 300);
    public static final zzbce zzI = zzbce.zzh(1, "gads:video_stream_cache:notify_interval_millis", 125, 125);
    public static final zzbce zzJ = zzbce.zzg(1, "gads:video_stream_cache:connect_timeout_millis", 10000, 10000);
    public static final zzbce zzK = new zzbcc(1, "gads:video:metric_frame_hash_times", "", "");
    public static final zzbce zzL = zzbce.zzh(1, "gads:video:metric_frame_hash_time_leniency", 500, 500);
    public static final zzbce zzM = new zzbby(1, "gads:video:force_watermark", false, false);
    public static final zzbce zzN = zzbce.zzh(1, "gads:video:surface_update_min_spacing_ms", 1000, 1000);
    public static final zzbce zzO = new zzbby(1, "gads:video:spinner:enabled", false, false);
    public static final zzbce zzP = new zzbby(1, "gads:video:shutter:enabled", false, false);
    public static final zzbce zzQ = zzbce.zzg(1, "gads:video:spinner:scale", 4, 4);
    public static final zzbce zzR = zzbce.zzh(1, "gads:video:spinner:jank_threshold_ms", 50, 50);
    public static final zzbce zzS = new zzbby(1, "gads:video:aggressive_media_codec_release", false, false);
    public static final zzbce zzT = new zzbcc(1, "gads:video:codec_query_mime_types", "", "");
    public static final zzbce zzU = zzbce.zzg(1, "gads:video:codec_query_minimum_version", 16, 16);
    public static final zzbce zzV = new zzbcc(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_banner.js", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_banner.js");
    public static final zzbce zzW = new zzbcc(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_expanded_banner.js", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_expanded_banner.js");
    public static final zzbce zzX = new zzbcc(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_interstitial.js", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_interstitial.js");
    public static final zzbce zzY = new zzbcc(1, "gad:mraid:version", "3.0", "3.0");
    public static final zzbce zzZ = new zzbby(1, "gads:mraid:expanded_interstitial_fix", false, false);
    public static final zzbce zza = new zzbcc(1, "gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    public static final zzbce zzaA = new zzbby(1, "gads:sai:server_side_npa:disable_writing", false, false);
    public static final zzbce zzaB = new zzbby(1, "gads:sai:server_side_npa:enabled", true, true);
    public static final zzbce zzaC = new zzbcc(1, "gads:sai:server_side_npa:shared_preference_key_list", "{  \"__default__\": [    \"IABTCF_TCString\"  ],  \"mobileads_consent\": [    \"consent_string\"  ]}", "{  \"__default__\": [    \"IABTCF_TCString\"  ],  \"mobileads_consent\": [    \"consent_string\"  ]}");
    public static final zzbce zzaD = new zzbby(1, "gads:disables_app_measurement_sdk_init", false, false);
    public static final zzbce zzaE = new zzbby(1, "gads:idless:internal_state_enabled", true, true);
    public static final zzbce zzaF = new zzbby(1, "gads:idless:idless_disables_offline_ads_signalling", true, true);
    public static final zzbce zzaG = new zzbby(1, "gads:custom_idless:enabled", true, true);
    public static final zzbce zzaH = new zzbcc(1, "gads:idless:cookie_modification", "=; Max-Age=-1; path=/; domain=.doubleclick.net", "=; Max-Age=-1; path=/; domain=.doubleclick.net");
    public static final zzbce zzaI = new zzbby(1, "gads:idless_sdk_core_only:enabled", false, false);
    public static final zzbce zzaJ = new zzbby(1, "gads:interstitial:app_must_be_foreground:enabled", false, false);
    public static final zzbce zzaK = new zzbby(1, "gads:interstitial:foreground_report:enabled", false, false);
    public static final zzbce zzaL = new zzbby(1, "gads:interstitial:default_immersive", false, false);
    public static final zzbce zzaM = new zzbby(1, "gads:interstitial:hide_status_bar_multiwindow", true, true);
    public static final zzbce zzaN = new zzbby(1, "gads:interstitial:hide_status_bar_transparent_background", true, true);
    public static final zzbce zzaO = new zzbby(1, "gads:appopen:default_immersive", false, false);
    public static final zzbce zzaP = zzbce.zzg(1, "gads:show_interstitial_with_context:min_version", 204890000, 204890000);
    public static final zzbce zzaQ = new zzbby(1, "gads:interstitial:ad_overlay_omit_ad_html", true, true);
    public static final zzbce zzaR = new zzbby(1, "gads:webview:error_web_response:enabled", false, false);
    public static final zzbce zzaS = new zzbby(1, "gads:webview:set_fixed_text_zoom", true, true);
    public static final zzbce zzaT = new zzbby(1, "gads:webviewgone:kill_process:enabled", false, false);
    public static final zzbce zzaU = new zzbby(1, "gads:webviewgone:new_onshow:enabled", false, false);
    public static final zzbce zzaV = new zzbcc(1, "gads:webview_cookie_url", "https://googleads.g.doubleclick.net", "https://googleads.g.doubleclick.net");
    public static final zzbce zzaW = new zzbby(1, "gads:webview_cookie_filter:enabled", true, true);
    public static final zzbce zzaX = new zzbby(1, "gads:rewarded:adapter_initialization_enabled", false, false);
    public static final zzbce zzaY = new zzbby(1, "gads:rewarded:ad_metadata_enabled", true, true);
    public static final zzbce zzaZ = zzbce.zzh(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500, 500);
    public static final zzbce zzaa = new zzbby(1, "gads:mraid:initial_size_fallback", false, false);
    public static final zzbce zzab = zzbce.zzg(1, "gads:content_vertical_fingerprint_number", 100, 100);
    public static final zzbce zzac = zzbce.zzg(1, "gads:content_vertical_fingerprint_bits", 23, 23);
    public static final zzbce zzad = zzbce.zzg(1, "gads:content_vertical_fingerprint_ngram", 3, 3);
    public static final zzbce zzae = new zzbcc(1, "gads:content_fetch_view_tag_id", "googlebot", "googlebot");
    public static final zzbce zzaf = new zzbcc(1, "gads:content_fetch_exclude_view_tag", "none", "none");
    public static final zzbce zzag = new zzbby(1, "gads:content_fetch_disable_get_title_from_webview", false, false);
    public static final zzbce zzah = new zzbby(1, "gads:content_fetch_enable_new_content_score", false, false);
    public static final zzbce zzai = new zzbby(1, "gads:content_fetch_enable_serve_once", false, false);
    public static final zzbce zzaj = new zzbby(1, "gads:parse_analytics_event_map", true, true);
    public static final zzbce zzak = new zzbby(1, "gads:sai:enabled", true, true);
    public static final zzbce zzal = new zzbcc(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzbce zzam = new zzbcc(1, "gads:sai:impression_ping_schema_v2", "^[^?]*(/adview|/pcs/view).*", "^[^?]*(/adview|/pcs/view).*");
    public static final zzbce zzan = new zzbby(1, "gads:sai:logging_disabled_without_macro", false, false);
    public static final zzbce zzao = new zzbby(1, "gads:sai:using_macro:enabled", true, true);
    public static final zzbce zzap = new zzbcc(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]", "[gw_fbsaeid]");
    public static final zzbce zzaq = zzbce.zzh(1, "gads:sai:timeout_ms", -1, -1);
    public static final zzbce zzar = zzbce.zzg(1, "gads:sai:scion_thread_pool_size", 5, 5);
    public static final zzbce zzas = new zzbby(1, "gads:sai:app_measurement_enabled3", true, true);
    public static final zzbce zzat = zzbce.zzg(1, "gads:sai:app_measurement_min_client_dynamite_version", 20290, 20290);
    public static final zzbce zzau = new zzbby(1, "gads:sai:force_through_reflection", true, true);
    public static final zzbce zzav = new zzbby(1, "gads:sai:gmscore_availability_check_disabled", false, false);
    public static final zzbce zzaw = new zzbby(1, "gads:sai:logging_disabled_for_drx", true, true);
    public static final zzbce zzax = new zzbby(1, "gads:sai:app_measurement_npa_enabled", false, false);
    public static final zzbce zzay = new zzbby(1, "gads:idless:idless_disables_attestation", true, true);
    public static final zzbce zzaz = new zzbby(1, "gads:idless:app_measurement_idless_enabled", true, true);
    public static final zzbce zzb = zzbce.zzg(1, "gads:js_eng_load_gmsg:timeout_millis", 10000, 10000);
    public static final zzbce zzbA = new zzbby(1, "gads:include_failure_to_instantiate_adapter:enabled", true, true);
    public static final zzbce zzbB = new zzbby(1, "gads:presentation_error:urls_enabled", true, true);
    public static final zzbce zzbC = new zzbby(1, "gads:rtb_interstitial:use_fullscreen_monitor", true, true);
    public static final zzbce zzbD = new zzbby(1, "gads:native_required_assets:enabled", true, true);
    public static final zzbce zzbE = new zzbby(1, "gads:native_required_assets:check_inner_mediaview:enabled", true, true);
    public static final zzbce zzbF = new zzbby(1, "gads:include_timeout_in_rtb_signals:enabled", true, true);
    public static final zzbce zzbG = new zzbby(1, "gads:include_signal_error_code_in_rtb_signals:enabled", true, true);
    public static final zzbce zzbH = new zzbby(1, "gads:include_latency_in_rtb_signals:enabled", false, false);
    public static final zzbce zzbI = new zzbby(1, "gads:include_adapter_error_code_in_ans:enabled", true, true);
    public static final zzbce zzbJ = new zzbby(1, "gads:include_adapter_initialization_status_in_rtb_signals:enabled", false, false);
    public static final zzbce zzbK = new zzbby(1, "gads:remove_rtb_adapter_cache:enabled", true, true);
    public static final zzbce zzbL = new zzbcc(1, "gad:scar_rtb_signal:enabled_list", "", "");
    public static final zzbce zzbM = new zzbby(1, "gads:call_rtb_adapters:separate_background_thread:enabled", false, false);
    public static final zzbce zzbN = zzbce.zzg(1, "gads:native_ad_options_rtb:min_version", 204890000, 204890000);
    public static final zzbce zzbO = new zzbby(1, "gads:track_view_next_runloop:enabled", false, false);
    public static final zzbce zzbP = new zzbby(1, "gads:synchronize_measurement_listener:enabled", false, false);
    public static final zzbce zzbQ = new zzbby(1, "gads:native_required_assets:viewability:enabled", false, false);
    public static final zzbce zzbR = new zzbby(1, "gads:signal_adapters:enabled", true, true);
    public static final zzbce zzbS = new zzbby(1, "gads:read_from_adapter_settings:enabled", true, true);
    public static final zzbce zzbT = zzbce.zzg(1, "gads:adapter_initialization:min_sdk_version", 15301000, 15301000);
    public static final zzbce zzbU = zzbce.zzh(1, "gads:adapter_initialization:timeout", 30, 30);
    public static final zzbce zzbV = zzbce.zzh(1, "gads:adapter_initialization:cld_timeout", 10, 10);
    public static final zzbce zzbW = new zzbby(1, "gads:additional_video_csi:enabled", true, true);
    public static final zzbce zzbX = new zzbby(1, "gads:multiple_video_playback:enabled", true, true);
    public static final zzbce zzbY = new zzbby(1, "gads:pause_time_update_when_video_completed:enabled", false, false);
    public static final zzbce zzbZ = new zzbby(1, "gads:video:use_range_http_data_source", false, false);
    public static final zzbce zzba = zzbce.zzh(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5), TimeUnit.MINUTES.toMillis(5));
    public static final zzbce zzbb = new zzbby(1, "gads:adid_values_in_adrequest:enabled", true, true);
    public static final zzbce zzbc = zzbce.zzh(1, "gads:adid_values_in_adrequest:timeout", 2000, 2000);
    public static final zzbce zzbd = new zzbby(1, "gads:disable_adid_values_in_ms", true, true);
    public static final zzbce zzbe = zzbce.zzh(1, "gads:ad_overlay:delay_page_close_timeout_ms", CoroutineLiveDataKt.DEFAULT_TIMEOUT, CoroutineLiveDataKt.DEFAULT_TIMEOUT);
    public static final zzbce zzbf = new zzbby(1, "gads:custom_close_blocking:enabled", true, true);
    public static final zzbce zzbg = new zzbby(1, "gads:disabling_closable_area:enabled", true, true);
    public static final zzbce zzbh = new zzbby(1, "gads:force_top_right_close_button:enabled", true, true);
    public static final zzbce zzbi = new zzbcc(1, "gads:close_button_asset_name", "white", "white");
    public static final zzbce zzbj = zzbce.zzh(1, "gads:close_button_fade_in_duration_ms", 0, 0);
    public static final zzbce zzbk = new zzbby(1, "gads:disable_click_during_fade_in", false, false);
    public static final zzbce zzbl = new zzbby(1, "gads:use_system_ui_for_fullscreen:enabled", false, false);
    public static final zzbce zzbm = new zzbby(1, "gads:ad_overlay:collect_cutout_info:enabled", false, false);
    public static final zzbce zzbn = zzbce.zzg(1, "gads:banner_refresh_time:seconds", 60, 60);
    public static final zzbce zzbo = new zzbby(1, "gads:server_transaction_for_banner_refresh:enabled", false, false);
    public static final zzbce zzbp = new zzbby(1, "gads:pause_banner_webview_on_load:enabled", false, false);
    public static final zzbce zzbq = new zzbcc(1, "gads:spherical_video:vertex_shader", "", "");
    public static final zzbce zzbr = new zzbcc(1, "gads:spherical_video:fragment_shader", "", "");
    public static final zzbce zzbs = new zzbby(1, "gads:include_local_global_rectangles", false, false);
    public static final zzbce zzbt = zzbce.zzh(1, "gads:position_watcher:throttle_ms", 200, 200);
    public static final zzbce zzbu = zzbce.zzh(1, "gads:position_watcher:scroll_aware_throttle_ms", 33, 33);
    public static final zzbce zzbv = new zzbby(1, "gads:position_watcher:enable_scroll_aware_ads", false, false);
    public static final zzbce zzbw = new zzbby(1, "gads:position_watcher:send_scroll_data", false, false);
    public static final zzbce zzbx = new zzbcc(1, "gads:logged_adapter_version_classes", "", "");
    public static final zzbce zzby = zzbce.zzh(1, "gads:rtb_v1_1:signal_timeout_ms", 1000, 1000);
    public static final zzbce zzbz = new zzbcc(1, "gads:rtb_logging:regex", "(?!)", "(?!)");
    public static final zzbce zzc = zzbce.zzg(1, "gads:js_eng_full_load:timeout_millis", 60000, 60000);
    public static final zzbce zzcA = new zzbby(1, "gads:msa:experiments:incapigass:enabled", false, false);
    public static final zzbce zzcB = new zzbcc(1, "gads:msa:experiments:incapi:trusted_cert", "308204433082032ba003020102020900c2e08746644a308d300d06092a864886f70d01010405003074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f6964301e170d3038303832313233313333345a170d3336303130373233313333345a3074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f696430820120300d06092a864886f70d01010105000382010d00308201080282010100ab562e00d83ba208ae0a966f124e29da11f2ab56d08f58e2cca91303e9b754d372f640a71b1dcb130967624e4656a7776a92193db2e5bfb724a91e77188b0e6a47a43b33d9609b77183145ccdf7b2e586674c9e1565b1f4c6a5955bff251a63dabf9c55c27222252e875e4f8154a645f897168c0b1bfc612eabf785769bb34aa7984dc7e2ea2764cae8307d8c17154d7ee5f64a51a44a602c249054157dc02cd5f5c0e55fbef8519fbe327f0b1511692c5a06f19d18385f5c4dbc2d6b93f68cc2979c70e18ab93866b3bd5db8999552a0e3b4c99df58fb918bedc182ba35e003c1b4b10dd244a8ee24fffd333872ab5221985edab0fc0d0b145b6aa192858e79020103a381d93081d6301d0603551d0e04160414c77d8cc2211756259a7fd382df6be398e4d786a53081a60603551d2304819e30819b8014c77d8cc2211756259a7fd382df6be398e4d786a5a178a4763074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f6964820900c2e08746644a308d300c0603551d13040530030101ff300d06092a864886f70d010104050003820101006dd252ceef85302c360aaace939bcff2cca904bb5d7a1661f8ae46b2994204d0ff4a68c7ed1a531ec4595a623ce60763b167297a7ae35712c407f208f0cb109429124d7b106219c084ca3eb3f9ad5fb871ef92269a8be28bf16d44c8d9a08e6cb2f005bb3fe2cb96447e868e731076ad45b33f6009ea19c161e62641aa99271dfd5228c5c587875ddb7f452758d661f6cc0cccb7352e424cc4365c523532f7325137593c4ae341f4db41edda0d0b1071a7c440f0fe9ea01cb627ca674369d084bd2fd911ff06cdbf2cfa10dc0f893ae35762919048c7efc64c7144178342f70581c9de573af55b390dd7fdb9418631895d5f759f30112687ff621410c069308a", "308204433082032ba003020102020900c2e08746644a308d300d06092a864886f70d01010405003074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f6964301e170d3038303832313233313333345a170d3336303130373233313333345a3074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f696430820120300d06092a864886f70d01010105000382010d00308201080282010100ab562e00d83ba208ae0a966f124e29da11f2ab56d08f58e2cca91303e9b754d372f640a71b1dcb130967624e4656a7776a92193db2e5bfb724a91e77188b0e6a47a43b33d9609b77183145ccdf7b2e586674c9e1565b1f4c6a5955bff251a63dabf9c55c27222252e875e4f8154a645f897168c0b1bfc612eabf785769bb34aa7984dc7e2ea2764cae8307d8c17154d7ee5f64a51a44a602c249054157dc02cd5f5c0e55fbef8519fbe327f0b1511692c5a06f19d18385f5c4dbc2d6b93f68cc2979c70e18ab93866b3bd5db8999552a0e3b4c99df58fb918bedc182ba35e003c1b4b10dd244a8ee24fffd333872ab5221985edab0fc0d0b145b6aa192858e79020103a381d93081d6301d0603551d0e04160414c77d8cc2211756259a7fd382df6be398e4d786a53081a60603551d2304819e30819b8014c77d8cc2211756259a7fd382df6be398e4d786a5a178a4763074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f6964820900c2e08746644a308d300c0603551d13040530030101ff300d06092a864886f70d010104050003820101006dd252ceef85302c360aaace939bcff2cca904bb5d7a1661f8ae46b2994204d0ff4a68c7ed1a531ec4595a623ce60763b167297a7ae35712c407f208f0cb109429124d7b106219c084ca3eb3f9ad5fb871ef92269a8be28bf16d44c8d9a08e6cb2f005bb3fe2cb96447e868e731076ad45b33f6009ea19c161e62641aa99271dfd5228c5c587875ddb7f452758d661f6cc0cccb7352e424cc4365c523532f7325137593c4ae341f4db41edda0d0b1071a7c440f0fe9ea01cb627ca674369d084bd2fd911ff06cdbf2cfa10dc0f893ae35762919048c7efc64c7144178342f70581c9de573af55b390dd7fdb9418631895d5f759f30112687ff621410c069308a");
    public static final zzbce zzcC = new zzbcc(1, "gads:msa:experiments:incapi:debug_cert", "308204a830820390a003020102020900d585b86c7dd34ef5300d06092a864886f70d0101040500308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d301e170d3038303431353233333635365a170d3335303930313233333635365a308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d30820120300d06092a864886f70d01010105000382010d00308201080282010100d6ce2e080abfe2314dd18db3cfd3185cb43d33fa0c74e1bdb6d1db8913f62c5c39df56f846813d65bec0f3ca426b07c5a8ed5a3990c167e76bc999b927894b8f0b22001994a92915e572c56d2a301ba36fc5fc113ad6cb9e7435a16d23ab7dfaeee165e4df1f0a8dbda70a869d516c4e9d051196ca7c0c557f175bc375f948c56aae86089ba44f8aa6a4dd9a7dbf2c0a352282ad06b8cc185eb15579eef86d080b1d6189c0f9af98b1c2ebd107ea45abdb68a3c7838a5e5488c76c53d40b121de7bbd30e620c188ae1aa61dbbc87dd3c645f2f55f3d4c375ec4070a93f7151d83670c16a971abe5ef2d11890e1b8aef3298cf066bf9e6ce144ac9ae86d1c1b0f020103a381fc3081f9301d0603551d0e041604148d1cc5be954c433c61863a15b04cbc03f24fe0b23081c90603551d230481c13081be80148d1cc5be954c433c61863a15b04cbc03f24fe0b2a1819aa48197308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d820900d585b86c7dd34ef5300c0603551d13040530030101ff300d06092a864886f70d0101040500038201010019d30cf105fb78923f4c0d7dd223233d40967acfce00081d5bd7c6e9d6ed206b0e11209506416ca244939913d26b4aa0e0f524cad2bb5c6e4ca1016a15916ea1ec5dc95a5e3a010036f49248d5109bbf2e1e618186673a3be56daf0b77b1c229e3c255e3e84c905d2387efba09cbf13b202b4e5a22c93263484a23d2fc29fa9f1939759733afd8aa160f4296c2d0163e8182859c6643e9c1962fa0c18333335bc090ff9a6b22ded1ad444229a539a94eefadabd065ced24b3e51e5dd7b66787bef12fe97fba484c423fb4ff8cc494c02f0f5051612ff6529393e8e46eac5bb21f277c151aa5f2aa627d1e89da70ab6033569de3b9897bfff7ca9da3e1243f60b", "308204a830820390a003020102020900d585b86c7dd34ef5300d06092a864886f70d0101040500308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d301e170d3038303431353233333635365a170d3335303930313233333635365a308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d30820120300d06092a864886f70d01010105000382010d00308201080282010100d6ce2e080abfe2314dd18db3cfd3185cb43d33fa0c74e1bdb6d1db8913f62c5c39df56f846813d65bec0f3ca426b07c5a8ed5a3990c167e76bc999b927894b8f0b22001994a92915e572c56d2a301ba36fc5fc113ad6cb9e7435a16d23ab7dfaeee165e4df1f0a8dbda70a869d516c4e9d051196ca7c0c557f175bc375f948c56aae86089ba44f8aa6a4dd9a7dbf2c0a352282ad06b8cc185eb15579eef86d080b1d6189c0f9af98b1c2ebd107ea45abdb68a3c7838a5e5488c76c53d40b121de7bbd30e620c188ae1aa61dbbc87dd3c645f2f55f3d4c375ec4070a93f7151d83670c16a971abe5ef2d11890e1b8aef3298cf066bf9e6ce144ac9ae86d1c1b0f020103a381fc3081f9301d0603551d0e041604148d1cc5be954c433c61863a15b04cbc03f24fe0b23081c90603551d230481c13081be80148d1cc5be954c433c61863a15b04cbc03f24fe0b2a1819aa48197308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d820900d585b86c7dd34ef5300c0603551d13040530030101ff300d06092a864886f70d0101040500038201010019d30cf105fb78923f4c0d7dd223233d40967acfce00081d5bd7c6e9d6ed206b0e11209506416ca244939913d26b4aa0e0f524cad2bb5c6e4ca1016a15916ea1ec5dc95a5e3a010036f49248d5109bbf2e1e618186673a3be56daf0b77b1c229e3c255e3e84c905d2387efba09cbf13b202b4e5a22c93263484a23d2fc29fa9f1939759733afd8aa160f4296c2d0163e8182859c6643e9c1962fa0c18333335bc090ff9a6b22ded1ad444229a539a94eefadabd065ced24b3e51e5dd7b66787bef12fe97fba484c423fb4ff8cc494c02f0f5051612ff6529393e8e46eac5bb21f277c151aa5f2aa627d1e89da70ab6033569de3b9897bfff7ca9da3e1243f60b");
    public static final zzbce zzcD = new zzbby(1, "gads:gestures:clearTd:enabled", true, true);
    public static final zzbdx zzcE = zzbeq.zzb;
    public static final zzbce zzcF = new zzbby(1, "gads:gestures:errorlogging:enabled", false, false);
    public static final zzbce zzcG = zzbce.zzh(1, "gads:gestures:task_timeout", 2000, 2000);
    public static final zzbce zzcH = new zzbby(1, "gads:gestures:asig:enabled", true, true);
    public static final zzbce zzcI = new zzbby(1, "gads:gestures:ans:enabled", false, false);
    public static final zzbce zzcJ = new zzbby(1, "gads:gestures:tos:enabled", false, false);
    public static final zzbce zzcK = new zzbby(1, "gads:gestures:imd:enabled", true, true);
    public static final zzbce zzcL = new zzbby(1, "gads:msa:tt:enabled", true, true);
    public static final zzbce zzcM = new zzbby(1, "gads:msa:ait:enabled", false, false);
    public static final zzbce zzcN = zzbce.zzg(1, "gads:gestures:qst:enabled", -2, -2);
    public static final zzbce zzcO = zzbce.zzg(1, "gads:gestures:qst:to", 100, 100);
    public static final zzbce zzcP = zzbce.zzg(1, "gads:signal:app_start:tw", 1000, 1000);
    public static final zzbce zzcQ = new zzbby(1, "gads:msa:gct:enabled", false, false);
    public static final zzbce zzcR = zzbce.zzg(1, "gads:msa:ait:to", 5000, 5000);
    public static final zzbce zzcS = new zzbby(1, "gads:gestures:pvst:enabled", true, true);
    public static final zzbce zzcT = new zzbby(1, "gads:gestures:pvstnw:enabled", false, false);
    public static final zzbce zzcU = new zzbby(1, "gads:gestures:fpi:enabled", false, false);
    public static final zzbce zzcV = new zzbby(1, "gads:signal:app_permissions:disabled", false, false);
    public static final zzbce zzcW = new zzbby(1, "gads:signal:app_set_id_info_in_ad_request:enabled", true, true);
    public static final zzbce zzcX = new zzbby(1, "gads:signal:app_set_id_info_signal_latency_fix:enabled", true, true);
    public static final zzbce zzcY = new zzbby(1, "gads:app_set_id_info_signal:timeout:enabled", true, true);
    public static final zzbce zzcZ = zzbce.zzh(1, "gads:app_set_id_info_signal:timeout:millis", 2000, 2000);
    public static final zzbce zzca = zzbce.zzh(1, "gads:video:range_http_data_source_high_water_mark", 614400, 614400);
    public static final zzbce zzcb = zzbce.zzh(1, "gads:video:range_http_data_source_low_water_mark", 102400, 102400);
    public static final zzbce zzcc = new zzbby(1, "gads:run_exoplayer_video_stream_task_in_ui_thread:enabled", true, true);
    public static final zzbce zzcd = new zzbby(1, "gads:csi:enabled_per_sampling", false, false);
    public static final zzbce zzce = new zzbby(1, "gads:always_set_transfer_listener:enabled", false, false);
    public static final zzbce zzcf = new zzbby(1, "gads:initialization_csi:enabled", false, false);
    public static final zzbce zzcg = new zzbby(1, "gads:csi:enable_csi_latency_reporting", false, false);
    public static final zzbce zzch = new zzbby(1, "gads:csi:enable_csi_latency_reporting_v2", false, false);
    public static final zzbce zzci = new zzbby(1, "gads:csi:enable_csi_latency_reporting_v3", false, false);
    public static final zzbce zzcj = new zzbby(1, "gads:csi:enable_csi_latency_reporting_v4", false, false);
    public static final zzbce zzck = new zzbby(1, "gads:csi:enable_csi_latency_reporting_for_rendering", false, false);
    public static final zzbce zzcl = new zzbby(1, "gads:csi:enable_is_native_sra_for_rendering_latency", false, false);
    public static final zzbce zzcm = new zzbby(1, "gads:csi:enable_csi_latency_individual_signals", false, false);
    public static final zzbce zzcn = new zzbby(1, "gads:csi:enable_memory_info", false, false);
    public static final zzbce zzco = new zzbby(1, "gads:csi:enable_app_version", false, false);
    public static final zzbce zzcp = new zzbby(1, "gads:optional_signal_timeout_exception:enabled", false, false);
    public static final zzbce zzcq = new zzbby(1, "gads:optional_signal_timeout_micros:enabled", false, false);
    public static final zzbce zzcr = new zzbby(1, "gads:empty_stacktrace_exception_reporting:enabled", false, false);
    public static final zzbce zzcs = new zzbby(1, "gads:plugin_info_csi:enabled", true, true);
    public static final zzbce zzct = new zzbby(1, "gads:msa:experiments:ps:enabled", true, true);
    public static final zzbce zzcu = new zzbby(1, "gads:msa:experiments:fb:enabled", true, true);
    public static final zzbce zzcv = new zzbby(1, "gads:msa:experiments:ps:er", true, true);
    public static final zzbce zzcw = new zzbby(1, "gads:msa:experiments:a2", true, true);
    public static final zzbce zzcx = new zzbby(1, "gads:msa:experiments:log", false, false);
    public static final zzbce zzcy = new zzbby(1, "gads:msa:experiments:vfb", true, true);
    public static final zzbce zzcz = new zzbby(1, "gads:msa:experiments:incapi:enabled", true, true);
    public static final zzbce zzd = new zzbcc(1, "gads:video_exo_player:version", ExifInterface.GPS_MEASUREMENT_3D, ExifInterface.GPS_MEASUREMENT_3D);
    public static final zzbce zzdA = new zzbby(1, "gads:native:asset_view_touch_events", false, false);
    public static final zzbce zzdB = new zzbby(1, "gads:native:set_touch_listener_on_asset_views", true, true);
    public static final zzbce zzdC = new zzbby(1, "gads:update_touch_native_image_webview", false, false);
    public static final zzbce zzdD = new zzbby(1, "gads:ais:enabled", true, true);
    public static final zzbce zzdE = new zzbby(1, "gads:rewarded:ssv_options_holder_holder:enabled", true, true);
    public static final zzbce zzdF = new zzbby(1, "gads:rewarded:pass_ssv_options_holder_recursively:enabled", true, true);
    public static final zzbce zzdG = new zzbby(1, "gads:recursive:adapter_response_info:enabled", true, true);
    public static final zzbce zzdH = new zzbby(1, "gads:preqs:increment_recursively:enabled", true, true);
    public static final zzbce zzdI = new zzbby(1, "gads:send_fill_urls_recursively:enabled", true, true);
    public static final zzbce zzdJ = new zzbby(1, "gads:native_plus_banner:result_accumulator:enabled", true, true);
    public static final zzbce zzdK = new zzbby(1, "gads:stav:enabled", true, true);
    public static final zzbce zzdL = new zzbby(1, "gads:spam:impression_ui_idle:enable", true, true);
    public static final zzbce zzdM = zzbce.zzg(1, "gads:gass:impression_retry:count", 0, 0);
    public static final zzbce zzdN = zzbce.zzg(1, "gads:gass:impression_retry:delay_ms", 400, 400);
    public static final zzbce zzdO = new zzbcc(1, "gads:sdk_core_constants:caps", "", "");
    public static final zzbce zzdP = new zzbcc(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final zzbce zzdQ = new zzbcc(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzbce zzdR = zzbce.zzg(1, "gads:native_video_load_timeout", 10, 10);
    public static final zzbce zzdS = new zzbcc(1, "gads:ad_choices_content_description", "Ad Choices Icon", "Ad Choices Icon");
    public static final zzbce zzdT = new zzbby(1, "gads:enable_singleton_broadcast_receiver", true, true);
    public static final zzbce zzdU = new zzbby(1, "gads:native:media_view_match_parent:enabled", true, true);
    public static final zzbce zzdV = new zzbby(1, "gads:video:restrict_inside_web_view:enabled", false, false);
    public static final zzbce zzdW = new zzbby(1, "gads:native:count_impression_for_assets", false, false);
    public static final zzbce zzdX = new zzbby(1, "gads:native:enable_enigma_watermarking", true, true);
    public static final zzbce zzdY = new zzbby(1, "gads:native:handle_video_ftl", true, true);
    public static final zzbce zzdZ = new zzbby(1, "gads:fluid_ad:use_wrap_content_height", false, false);
    public static final zzbce zzda = new zzbby(1, "gads:caching_app_set_id_info:enabled", true, true);
    public static final zzbce zzdb = new zzbby(1, "gads:signal:app_set_id_info_under_gmscore:enabled", false, false);
    public static final zzbce zzdc = new zzbby(1, "gads:signal:app_set_id_info_for_scar:enabled", true, true);
    public static final zzbce zzdd = new zzbby(1, "gads:signal:paid_v1_in_ad_request:enabled", true, true);
    public static final zzbce zzde = new zzbby(1, "gads:signal:paid_v2_in_ad_request:enabled", true, true);
    public static final zzbce zzdf = new zzbby(1, "gads:signal:paid_v1_in_gam_ad_request:enabled", true, true);
    public static final zzbce zzdg = new zzbby(1, "gads:signal:paid_v2_in_gam_ad_request:enabled", true, true);
    public static final zzbce zzdh = new zzbby(1, "gads:signal:paid_on_gam:enabled", true, true);
    public static final zzbce zzdi = new zzbby(1, "gads:signal:paid_v1_3p_on_admob:enabled", false, false);
    public static final zzbce zzdj = new zzbby(1, "gads:signal:paid_v1_3p_on_gam:enabled", false, false);
    public static final zzbce zzdk = zzbce.zzg(1, "gads:signal:paid_v2_min_client_jar_version", 223712000, 223712000);
    public static final zzbce zzdl = new zzbby(1, "gads:signal:clear_paid_v2_on_lower_than_v50", true, true);
    public static final zzbce zzdm = new zzbcc(1, "gads:ad_manager_ad_unit_pattern", "^\\/[0-9]*\\/.*|^\\/[0-9]*,[0-9]*\\/.*", "^\\/[0-9]*\\/.*|^\\/[0-9]*,[0-9]*\\/.*");
    public static final zzbce zzdn = new zzbcc(1, "gads:ad_mob_ad_unit_pattern", "^(ca-app-pub-[a-zA-Z0-9\\-]+)\\/([a-zA-Z0-9_\\-]+)(\\/.*)?$", "^(ca-app-pub-[a-zA-Z0-9\\-]+)\\/([a-zA-Z0-9_\\-]+)(\\/.*)?$");
    public static final zzbce zzdo = zzbce.zzh(1, "gads:signal:paid_v1_ttl", TimeUnit.HOURS.toMillis(4383), TimeUnit.HOURS.toMillis(4383));
    public static final zzbce zzdp = zzbce.zzh(1, "gads:signal:paid_v2_ttl", TimeUnit.DAYS.toMillis(390), TimeUnit.DAYS.toMillis(390));
    public static final zzbce zzdq = new zzbby(1, "gads:paidv2:user_option_gmsg_handlers:enabled", true, true);
    public static final zzbce zzdr = new zzbby(1, "gads:gestures:hpk:enabled", true, true);
    public static final zzbce zzds = new zzbby(1, "gads:gestures:check_initialization_thread:enabled", false, false);
    public static final zzbce zzdt = new zzbby(1, "gads:gestures:init_new_thread:enabled", true, true);
    public static final zzbce zzdu = new zzbby(1, "gads:gestures:pds:enabled", true, true);
    public static final zzbce zzdv = new zzbby(1, "gads:gestures:ns:enabled", true, true);
    public static final zzbce zzdw = new zzbby(1, "gads:gestures:vtm:enabled", true, true);
    public static final zzbce zzdx = new zzbby(1, "gads:gestures:vdd:enabled", false, false);
    public static final zzbce zzdy = new zzbby(1, "gads:gestures:asvs:enabled", true, true);
    public static final zzbce zzdz = new zzbby(1, "gads:gadsignalsdelegate_ui_thread_fix:enabled", true, true);
    public static final zzbce zze = zzbce.zzg(1, "gads:video_exo_player:connect_timeout", 8000, 8000);
    public static final zzbce zzeA = zzbce.zzg(1, "gads:max_preload_app_open_entries:count", 10, 10);
    public static final zzbce zzeB = new zzbby(1, "gads:chrome_custom_tabs_browser:enabled", false, false);
    public static final zzbce zzeC = new zzbby(1, "gads:chrome_custom_tabs:disabled", false, false);
    public static final zzbce zzeD = new zzbby(1, "gads:cct_v2_connection:enabled", false, false);
    public static final zzbce zzeE = new zzbby(1, "gads:cct_v2_csi:enabled", false, false);
    public static final zzbce zzeF = new zzbby(1, "gads:cct_v2_optimization:enabled", false, false);
    public static final zzbce zzeG = new zzbby(1, "gads:cct_v2_prewarm_at_init:enabled", false, false);
    public static final zzbce zzeH = new zzbby(2, "CHROME_CUSTOM_TAB_OPT_OUT", false, false);
    public static final zzbce zzeI = zzbce.zzh(1, "gads:debug_hold_gesture:time_millis", 2000, 2000);
    public static final zzbce zzeJ = new zzbcc(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice", "https://www.google.com/dfp/linkDevice");
    public static final zzbce zzeK = new zzbcc(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview", "https://www.google.com/dfp/inAppPreview");
    public static final zzbce zzeL = new zzbcc(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals", "https://www.google.com/dfp/debugSignals");
    public static final zzbce zzeM = new zzbcc(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData", "https://www.google.com/dfp/sendDebugData");
    public static final zzbce zzeN = zzbce.zzg(1, "gads:drx_debug:timeout_ms", 5000, 5000);
    public static final zzbce zzeO = zzbce.zzg(1, "gad:pixel_dp_comparision_multiplier", 1, 1);
    public static final zzbce zzeP = new zzbby(1, "gad:interstitial_notify_publisher_without_delay", false, false);
    public static final zzbce zzeQ = new zzbby(1, "gad:interstitial_for_multi_window", true, true);
    public static final zzbce zzeR = new zzbby(1, "gad:interstitial_ad_stay_active_in_multi_window", true, true);
    public static final zzbce zzeS = new zzbby(1, "gad:interstitial_multi_window_method", false, false);
    public static final zzbce zzeT = new zzbby(1, "gads:display_cutouts:enabled", false, false);
    public static final zzbce zzeU = zzbce.zzg(1, "gad:interstitial:close_button_padding_dip", 20, 20);
    public static final zzbce zzeV = new zzbby(1, "gads:clearcut_logging:enabled", false, false);
    public static final zzbce zzeW = new zzbby(1, "gads:clearcut_logging:write_to_file", false, false);
    public static final zzbce zzeX = new zzbby(1, "gad:publisher_testing:force_local_request:enabled", true, true);
    public static final zzbce zzeY = new zzbcc(1, "gad:publisher_testing:force_local_request:enabled_list", "", "");
    public static final zzbce zzeZ = new zzbcc(1, "gad:publisher_testing:force_local_request:disabled_list", "", "");
    public static final zzbce zzea = new zzbby(1, "gads:rtb_v1_1:fetch_app_settings_using_cld:enabled", true, true);
    public static final zzbce zzeb = new zzbby(1, "gads:refresh_cld_for_scar:enabled", false, false);
    public static final zzbce zzec = new zzbby(1, "gads:get_request_signals_cld:enabled", true, true);
    public static final zzbce zzed = new zzbby(1, "gads:set_cld_runnable_get_signals:enabled", false, false);
    public static final zzbce zzee = new zzbby(1, "gads:get_request_signals_common_cld:enabled", true, true);
    public static final zzbce zzef = new zzbby(1, "gads:include_time_since_last_cld_update:enabled", false, false);
    public static final zzbce zzeg = zzbce.zzg(1, "gads:include_time_since_last_cld_update_timeout:ms", ServiceStarter.ERROR_UNKNOWN, ServiceStarter.ERROR_UNKNOWN);
    public static final zzbce zzeh = new zzbby(1, "gads:rtb_v1_1:use_manifest_appid_cld:enabled", true, true);
    public static final zzbce zzei = zzbce.zzh(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000, 7200000);
    public static final zzbce zzej = zzbce.zzh(1, "gads:parental_controls:timeout", 2000, 2000);
    public static final zzbce zzek = new zzbby(1, "gads:cache:bind_on_foreground", false, false);
    public static final zzbce zzel = new zzbby(1, "gads:cache:bind_on_init", false, false);
    public static final zzbce zzem = new zzbby(1, "gads:cache:bind_on_request", false, false);
    public static final zzbce zzen = zzbce.zzh(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30), TimeUnit.SECONDS.toMillis(30));
    public static final zzbce zzeo = new zzbby(1, "gads:cache:use_cache_data_source", false, false);
    public static final zzbce zzep = new zzbby(1, "gads:cache:connection_per_read", true, true);
    public static final zzbce zzeq = zzbce.zzh(1, "gads:cache:connection_timeout", CoroutineLiveDataKt.DEFAULT_TIMEOUT, CoroutineLiveDataKt.DEFAULT_TIMEOUT);
    public static final zzbce zzer = zzbce.zzh(1, "gads:cache:read_only_connection_timeout", CoroutineLiveDataKt.DEFAULT_TIMEOUT, CoroutineLiveDataKt.DEFAULT_TIMEOUT);
    public static final zzbce zzes = new zzbby(1, "gads:cache:read_inner_data_source_if_gcache_miss", false, false);
    public static final zzbce zzet = new zzbby(1, "gads:cache:read_inner_data_source_if_gcache_not_downloaded", false, false);
    public static final zzbce zzeu = new zzbby(1, "gads:cache:report_web_intercept_gcache_exceptions:enabled", false, false);
    public static final zzbce zzev = new zzbby(1, "gads:http_assets_cache:enabled", false, false);
    public static final zzbce zzew = new zzbcc(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzbce zzex = zzbce.zzg(1, "gads:http_assets_cache:time_out", 100, 100);
    public static final zzbce zzey = zzbce.zzg(1, "gads:max_preload_interstitial_entries:count", 10, 10);
    public static final zzbce zzez = zzbce.zzg(1, "gads:max_preload_rewarded_entries:count", 10, 10);
    public static final zzbce zzf = zzbce.zzg(1, "gads:video_exo_player:read_timeout", 8000, 8000);
    public static final zzbce zzfA = new zzbby(1, "gads:nonagon:app_stats_main_thread:enabled", true, true);
    public static final zzbce zzfB = new zzbby(1, "gads:get_app_id_from_manifest_for_app_stats_signal:enabled", false, false);
    public static final zzbce zzfC = new zzbby(1, "gads:uri_query_to_map_bg_thread:enabled", false, false);
    public static final zzbce zzfD = new zzbcc(1, "gads:uri_query_to_map_bg_thread:types", "/result", "/result");
    public static final zzbce zzfE = zzbce.zzg(1, "gads:uri_query_to_map_bg_thread:min_length", 1000, 1000);
    public static final zzbce zzfF = new zzbby(1, "gads:nonagon:active_view_gmsg_background_thread:enabled", true, true);
    public static final zzbce zzfG = new zzbby(1, "gads:active_view_gmsg_separate_pool:enabled", true, true);
    public static final zzbce zzfH = new zzbby(1, "gads:nonagon:ad_load_on_failure_stack_trace:enabled", true, true);
    public static final zzbce zzfI = new zzbby(1, "gads:signals:ad_id_info:enabled", true, true);
    public static final zzbce zzfJ = new zzbby(1, "gads:signals:cache:enabled", true, true);
    public static final zzbce zzfK = new zzbby(1, "gads:signals:doritos:v1:enabled", true, true);
    public static final zzbce zzfL = new zzbby(1, "gads:signals:parental_control:enabled", true, true);
    public static final zzbce zzfM = new zzbby(1, "gads:signals:video_decoder:enabled", true, true);
    public static final zzbce zzfN = new zzbby(1, "gads:signals:banner_hardware_acceleration:enabled", false, false);
    public static final zzbce zzfO = new zzbby(1, "gads:signals:native_hardware_acceleration:enabled", false, false);
    public static final zzbce zzfP = new zzbby(1, "gads:signals:external_version:enabled", true, true);
    public static final zzbce zzfQ = zzbce.zzh(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000, 3600000);
    public static final zzbce zzfR = zzbce.zzg(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 26, 26);
    public static final zzbce zzfS = zzbce.zzg(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 999, 999);
    public static final zzbce zzfT = zzbce.zzg(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26, 26);
    public static final zzbce zzfU = zzbce.zzg(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27, 27);
    public static final zzbce zzfV = new zzbby(1, "gads:consent:shared_preference_reading:enabled", true, true);
    public static final zzbce zzfW = new zzbby(1, "gads:consent:iab_consent_info:enabled", true, true);
    public static final zzbce zzfX = new zzbby(1, "gads:fc_consent:shared_preference_reading:enabled", true, true);
    public static final zzbce zzfY = new zzbcc(1, "gads:sp:json_string", "[{\"sk\":\"personalized_ad_status\",\"type\":0,\"bk\":\"personalized_ad_status\"},{\"sk\":\"IABConsent_CMPPresent\",\"type\":2,\"bk\":\"IABConsent_CMPPresent\"},{\"sk\":\"IABConsent_SubjectToGDPR\",\"type\":0,\"bk\":\"IABConsent_SubjectToGDPR\"},{\"sk\":\"IABConsent_ConsentString\",\"type\":0,\"bk\":\"IABConsent_ConsentString\"},{\"sk\":\"IABConsent_ParsedPurposeConsents\",\"type\":0,\"bk\":\"IABConsent_ParsedPurposeConsents\"},{\"sk\":\"IABConsent_ParsedVendorConsents\",\"type\":0,\"bk\":\"IABConsent_ParsedVendorConsents\"},{\"sk\":\"IABTCF_TCString\",\"type\":0,\"bk\":\"IABTCF_TCString\"},{\"sk\":\"IABTCF_CmpSdkID\",\"type\":1,\"bk\":\"IABTCF_CmpSdkID\"},{\"sk\":\"IABTCF_gdprApplies\",\"type\":1,\"bk\":\"IABTCF_gdprApplies\"},{\"sk\":\"IABTCF_PolicyVersion\",\"type\":1,\"bk\":\"IABTCF_PolicyVersion\"},{\"sk\":\"IABTCF_PurposeConsents\",\"type\":0,\"bk\":\"IABTCF_PurposeConsents\"},{\"sk\":\"IABUSPrivacy_String\",\"type\":0,\"bk\":\"IABUSPrivacy_String\"},{\"sk\":\"IABTCF_AddtlConsent\",\"type\":0,\"bk\":\"IABTCF_AddtlConsent\"},{\"sk\":\"IABGPP_HDR_GppString\",\"type\":0,\"bk\":\"IABGPP_HDR_GppString\"},{\"sk\":\"IABGPP_GppSID\",\"type\":0,\"bk\":\"IABGPP_GppSID\"},{\"sk\":\"UPTC_UptcString\",\"type\":0,\"bk\":\"UPTC_UptcString\"},{\"sk\":\"gad_rdp\",\"type\":1,\"bk\":\"gad_rdp\"},{\"sk\":\"gad_has_consent_for_cookies\",\"type\":1,\"bk\":\"gad_has_consent_for_cookies\"}]", "[{\"sk\":\"personalized_ad_status\",\"type\":0,\"bk\":\"personalized_ad_status\"},{\"sk\":\"IABConsent_CMPPresent\",\"type\":2,\"bk\":\"IABConsent_CMPPresent\"},{\"sk\":\"IABConsent_SubjectToGDPR\",\"type\":0,\"bk\":\"IABConsent_SubjectToGDPR\"},{\"sk\":\"IABConsent_ConsentString\",\"type\":0,\"bk\":\"IABConsent_ConsentString\"},{\"sk\":\"IABConsent_ParsedPurposeConsents\",\"type\":0,\"bk\":\"IABConsent_ParsedPurposeConsents\"},{\"sk\":\"IABConsent_ParsedVendorConsents\",\"type\":0,\"bk\":\"IABConsent_ParsedVendorConsents\"},{\"sk\":\"IABTCF_TCString\",\"type\":0,\"bk\":\"IABTCF_TCString\"},{\"sk\":\"IABTCF_CmpSdkID\",\"type\":1,\"bk\":\"IABTCF_CmpSdkID\"},{\"sk\":\"IABTCF_gdprApplies\",\"type\":1,\"bk\":\"IABTCF_gdprApplies\"},{\"sk\":\"IABTCF_PolicyVersion\",\"type\":1,\"bk\":\"IABTCF_PolicyVersion\"},{\"sk\":\"IABTCF_PurposeConsents\",\"type\":0,\"bk\":\"IABTCF_PurposeConsents\"},{\"sk\":\"IABUSPrivacy_String\",\"type\":0,\"bk\":\"IABUSPrivacy_String\"},{\"sk\":\"IABTCF_AddtlConsent\",\"type\":0,\"bk\":\"IABTCF_AddtlConsent\"},{\"sk\":\"IABGPP_HDR_GppString\",\"type\":0,\"bk\":\"IABGPP_HDR_GppString\"},{\"sk\":\"IABGPP_GppSID\",\"type\":0,\"bk\":\"IABGPP_GppSID\"},{\"sk\":\"UPTC_UptcString\",\"type\":0,\"bk\":\"UPTC_UptcString\"},{\"sk\":\"gad_rdp\",\"type\":1,\"bk\":\"gad_rdp\"},{\"sk\":\"gad_has_consent_for_cookies\",\"type\":1,\"bk\":\"gad_has_consent_for_cookies\"}]");
    public static final zzbce zzfZ = new zzbby(1, "gads:nativeads:image:sample:enabled", true, true);
    public static final zzbce zzfa = zzbce.zzg(1, "gad:http_redirect_max_count:times", 8, 8);
    public static final zzbce zzfb = new zzbby(1, "gads:omid:enabled", true, true);
    public static final zzbce zzfc = zzbce.zzg(1, "gads:omid:destroy_webview_delay", 1000, 1000);
    public static final zzbce zzfd = new zzbby(1, "gads:omid_html_sessions_measure_webview:enabled", false, false);
    public static final zzbce zzfe = new zzbby(1, "gads:omid_javascript_session_service:enabled", false, false);
    public static final zzbce zzff = new zzbby(1, "gads:omid_javascript_session_service_log_success:enabled", false, false);
    public static final zzbce zzfg = new zzbcc(1, "gads:omid_settings_js_session_service_override_key", "javascript_session_service_enabled", "javascript_session_service_enabled");
    public static final zzbce zzfh = new zzbby(1, "gads:omid_use_base_64_encoding_for_native_html:enabled", true, true);
    public static final zzbce zzfi = new zzbby(1, "gads:omid_use_media_type_for_native:enabled", true, true);
    public static final zzbce zzfj = new zzbby(1, "gads:omid_use_impression_listener_full_screen:enabled", false, false);
    public static final zzbce zzfk = new zzbby(1, "gads:omid_native_display_webview_does_not_block:enabled", true, true);
    public static final zzbce zzfl = new zzbby(1, "gads:omid_native_display_webview_exp_report_exception", false, false);
    public static final zzbce zzfm = new zzbby(1, "gads:omid_signal_skip_ad_type_check:enabled", false, false);
    public static final zzbce zzfn = new zzbby(1, "gads:omid_cache_version_string:enabled", false, false);
    public static final zzbce zzfo = new zzbby(1, "gads:nonagon:app_open_app_switch_signal:enabled", true, true);
    public static final zzbce zzfp = new zzbby(1, "gads:nonagon:app_open_ad_show_emitter:enabled", true, true);
    public static final zzbce zzfq = new zzbcc(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)", "(?!)");
    public static final zzbce zzfr = new zzbby(1, "gads:nonagon:banner:check_dp_size", true, true);
    public static final zzbce zzfs = new zzbby(1, "gads:nonagon:rewarded:load_multiple_ads", true, true);
    public static final zzbce zzft = new zzbby(1, "gads:nonagon:return_no_fill_error_code", true, true);
    public static final zzbce zzfu = new zzbby(1, "gads:nonagon:continue_on_no_fill", true, true);
    public static final zzbce zzfv = new zzbby(1, "gads:nonagon:replace_no_ad_config_with_no_fill", true, true);
    public static final zzbce zzfw = new zzbby(1, "gads:nonagon:separate_timeout:enabled", true, true);
    public static final zzbce zzfx = zzbce.zzg(1, "gads:nonagon:request_timeout:seconds", 60, 60);
    public static final zzbce zzfy = new zzbby(1, "gads:nonagon:banner_recursive_renderer", true, true);
    public static final zzbce zzfz = new zzbby(1, "gads:nonagon:app_stats_lock:enabled", false, false);
    public static final zzbce zzg = zzbce.zzg(1, "gads:video_exo_player:loading_check_interval", 1048576, 1048576);
    public static final zzbce zzgA = zzbce.zzg(1, "gads:app_open_precache_pool:ad_time_limit", 14400, 14400);
    public static final zzbce zzgB = new zzbby(1, "gads:memory_leak:b129558083", true, true);
    public static final zzbce zzgC = new zzbby(1, "gads:unhandled_event_reporting:enabled", false, false);
    public static final zzbce zzgD = new zzbby(1, "gads:response_info:enabled", true, true);
    public static final zzbce zzgE = new zzbby(1, "gads:ad_source_response_info:enabled", true, true);
    public static final zzbce zzgF = new zzbby(1, "gads:loaded_adapter_response_response_info:enabled", true, true);
    public static final zzbce zzgG = new zzbby(1, "gads:response_info_extras:enabled", true, true);
    public static final zzbce zzgH = new zzbby(1, "gads:csi:interstitial_failed_to_show:enabled", true, true);
    public static final zzbce zzgI = new zzbby(1, "gads:csi:mediation_failure:enabled", true, true);
    public static final zzbce zzgJ = new zzbcc(1, "gads:csi:error_parsing:regex", "^(\\d+)", "^(\\d+)");
    public static final zzbce zzgK = new zzbby(1, "gads:csi:eids_from_cld:enabled", true, true);
    public static final zzbce zzgL = new zzbby(1, "gads:request_id_check:enabled", true, true);
    public static final zzbce zzgM = zzbce.zzg(1, "gads:maximum_query_json_cache_size", 200, 200);
    public static final zzbce zzgN = zzbce.zzh(1, "gads:timeout_query_json_cache:millis", 3600000, 3600000);
    public static final zzbce zzgO = new zzbby(1, "gads:scar_csi:enabled", true, true);
    public static final zzbce zzgP = new zzbby(1, "gads:scar_csi_sampling:enabled", false, false);
    public static final zzbce zzgQ = new zzbby(1, "gads:query_map_eviction_fullinfo:enabled", false, false);
    public static final zzbce zzgR = new zzbby(1, "gads:query_map_eviction_ping:enabled", false, false);
    public static final zzbce zzgS = new zzbby(1, "gads:disable_token_under_idless:enabled", true, true);
    public static final zzbce zzgT = new zzbby(1, "gads:scar_encryption_key_for_gbid:enabled", true, true);
    public static final zzbce zzgU = new zzbby(1, "gads:scar_v2:send_click_ping:enabled", false, false);
    public static final zzbce zzgV = new zzbby(1, "gads:scar_v2:send_impression_pings:enabled", false, false);
    public static final zzbce zzgW = new zzbby(1, "gads:scar:request_id_override:enabled", true, true);
    public static final zzbce zzgX = new zzbby(1, "gads:scar_v2:user_agent:enabled", true, true);
    public static final zzbce zzgY = new zzbcc(1, "gads:scar_v2:user_agent:key", "ua", "ua");
    public static final zzbce zzgZ = new zzbby(1, "gads:scar_v2:prior_click_count:enabled", true, true);
    public static final zzbce zzga = zzbce.zzg(1, "gads:nativeads:image:sample:pixels", 1048576, 1048576);
    public static final zzbce zzgb = new zzbby(1, "gads:nativeads:pub_image_scale_type:enabled", true, true);
    public static final zzbce zzgc = new zzbby(1, "gads:offline_signaling:enabled", false, false);
    public static final zzbce zzgd = zzbce.zzg(1, "gads:offline_signaling:log_maximum", 100, 100);
    public static final zzbce zzge = new zzbby(1, "gads:buffer_click_url_as_ready_to_ping:enabled", true, true);
    public static final zzbce zzgf = new zzbby(1, "gads:predictive_prefetch_from_cld:enabled", false, false);
    public static final zzbce zzgg = new zzbby(1, "gads:cache_layer_from_cld:enabled", false, false);
    public static final zzbce zzgh = new zzbby(1, "gads:cache_layer_wait_for_app_settings:enabled", false, false);
    public static final zzbce zzgi = new zzbby(1, "gads:precache_pool:verbose_logging", false, false);
    public static final zzbce zzgj = zzbce.zzg(1, "gads:rewarded_precache_pool:count", 0, 0);
    public static final zzbce zzgk = zzbce.zzg(1, "gads:interstitial_precache_pool:count", 0, 0);
    public static final zzbce zzgl = new zzbcc(1, "gads:rewarded_precache_pool:discard_strategy", "lru", "lru");
    public static final zzbce zzgm = new zzbcc(1, "gads:interstitial_precache_pool:discard_strategy", "lru", "lru");
    public static final zzbce zzgn = new zzbcc(1, "gads:rewarded_precache_pool:cache_start_trigger", "onAdClosed", "onAdClosed");
    public static final zzbce zzgo = new zzbcc(1, "gads:interstitial_precache_pool:cache_start_trigger", "onAdClosed", "onAdClosed");
    public static final zzbce zzgp = zzbce.zzg(1, "gads:rewarded_precache_pool:size", 1, 1);
    public static final zzbce zzgq = zzbce.zzg(1, "gads:interstitial_precache_pool:size", 1, 1);
    public static final zzbce zzgr = zzbce.zzg(1, "gads:rewarded_precache_pool:ad_time_limit", 1200, 1200);
    public static final zzbce zzgs = zzbce.zzg(1, "gads:interstitial_precache_pool:ad_time_limit", 1200, 1200);
    public static final zzbce zzgt = new zzbcc(1, "gads:rewarded_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzbce zzgu = new zzbcc(1, "gads:interstitial_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzbce zzgv = new zzbcc(1, "gads:app_open_precache_pool:schema", "orientation,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating", "orientation,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzbce zzgw = new zzbcc(1, "gads:app_open_precache_pool:discard_strategy", "oldest", "oldest");
    public static final zzbce zzgx = zzbce.zzg(1, "gads:app_open_precache_pool:count", 0, 0);
    public static final zzbce zzgy = new zzbcc(1, "gads:app_open_precache_pool:cache_start_trigger", "onAdClosed", "onAdClosed");
    public static final zzbce zzgz = zzbce.zzg(1, "gads:app_open_precache_pool:size", 1, 1);
    public static final zzbce zzh = zzbce.zzg(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE, Integer.MAX_VALUE);
    public static final zzbce zzhA = zzbce.zzg(1, "gads:interscroller:min_width", 300, 300);
    public static final zzbce zzhB = zzbce.zzg(1, "gads:interscroller:min_height", ItemTouchHelper.Callback.DEFAULT_SWIPE_ANIMATION_DURATION, ItemTouchHelper.Callback.DEFAULT_SWIPE_ANIMATION_DURATION);
    public static final zzbce zzhC = new zzbby(1, "gads:is_in_scroll_view_new_api:enabled", true, true);
    public static final zzbce zzhD = new zzbby(1, "gads:nas_collect_mediaview_matrix:enabled", true, true);
    public static final zzbce zzhE = new zzbby(1, "gads:nas_collect_layout_params:enabled", false, false);
    public static final zzbce zzhF = new zzbby(1, "gads:nas_collect_view_path:enabled", false, false);
    public static final zzbce zzhG = new zzbby(1, "gads:policy_validator_for_all_pubs:enabled", true, true);
    public static final zzbce zzhH = new zzbcc(1, "gad:publisher_testing:policy_validator:enabled_list", "", "");
    public static final zzbce zzhI = zzbce.zzg(1, "gads:policy_validator_layoutparam:flags", 808, 808);
    public static final zzbce zzhJ = new zzbby(2, "NATIVE_AD_DEBUGGER_ENABLED", true, true);
    public static final zzbce zzhK = zzbce.zzg(1, "gads:policy_validator_overlay_width:dp", 350, 350);
    public static final zzbce zzhL = zzbce.zzg(1, "gads:policy_validator_overlay_height:dp", 140, 140);
    public static final zzbce zzhM = new zzbby(1, "gads:use_wide_viewport:enabled", false, false);
    public static final zzbce zzhN = new zzbby(1, "gads:load_with_overview_mode:enabled", false, false);
    public static final zzbce zzhO = new zzbby(1, "gads:wire_banner_listener_after_request:enabled", false, false);
    public static final zzbce zzhP = new zzbby(1, "gads:wire_app_open_listener_after_request:enabled", false, false);
    public static final zzbce zzhQ = new zzbby(1, "gads:wire_interstitial_listener_after_request:enabled", false, false);
    public static final zzbce zzhR = new zzbcc(1, "gads:server_transaction_source:list", "Network", "Network");
    public static final zzbce zzhS = new zzbby(1, "gads:can_open_app_and_open_app_action:enabled", false, false);
    public static final zzbce zzhT = new zzbby(1, "gads:open_gmsg:set_uri_data_and_type:enabled", true, true);
    public static final zzbce zzhU = zzbce.zzg(1, "gads:ad_error_api:min_version", 202006000, 202006000);
    public static final zzbce zzhV = new zzbby(1, "gads:forward_bow_error_string:enabled", true, true);
    public static final zzbce zzhW = new zzbby(1, "gads:continue_on_process_response:enabled", true, true);
    public static final zzbce zzhX = zzbce.zzg(1, "gads:mediation_no_fill_error:min_version", 202510000, 202510000);
    public static final zzbce zzhY = new zzbby(1, "gads:line_item_no_fill_conversion:enabled", true, true);
    public static final zzbce zzhZ = zzbce.zzg(1, "gads:offline_database_version:version", 1, 1);
    public static final zzbce zzha = new zzbcc(1, "gads:scar_v2:prior_click_count:key", "pcc", "pcc");
    public static final zzbce zzhb = new zzbcc(1, "gads:scar_v2:pings_from_gma:key", "is_gma", "is_gma");
    public static final zzbce zzhc = new zzbby(1, "gads:scar:use_flag_regexes:enabled", true, true);
    public static final zzbce zzhd = new zzbcc(1, "gads:scar:google_click_paths", "/aclk,/pcs/click,/dbm/clk", "/aclk,/pcs/click,/dbm/clk");
    public static final zzbce zzhe = new zzbcc(1, "gads:scar:google_click_domain_suffixes", ".doubleclick.net,.googleadservices.com", ".doubleclick.net,.googleadservices.com");
    public static final zzbce zzhf = new zzbcc(1, "gads:scar:google_view_paths", "/pagead/adview,/pcs/view,/pagead/conversion,/dbm/ad", "/pagead/adview,/pcs/view,/pagead/conversion,/dbm/ad");
    public static final zzbce zzhg = new zzbcc(1, "gads:scar:google_view_domain_suffixes", ".doubleclick.net,.googleadservices.com,.googlesyndication.com", ".doubleclick.net,.googleadservices.com,.googlesyndication.com");
    public static final zzbce zzhh = new zzbby(1, "gads:scar:ping_non_google_urls:enabled", false, false);
    public static final zzbce zzhi = new zzbby(1, "gads:limit_scar_service_thread:enabled", false, false);
    public static final zzbce zzhj = new zzbby(1, "gads:ad_grouping_rendering:enabled", false, false);
    public static final zzbce zzhk = new zzbby(1, "gads:init_web_view_for_signal_collection_last:enabled", false, false);
    public static final zzbce zzhl = new zzbcc(1, "gads:discontinue_unknown_fmt_list", "", "");
    public static final zzbce zzhm = new zzbby(1, "gads:signal_collection_without_rendering:enabled", true, true);
    public static final zzbce zzhn = zzbce.zzg(1, "gads:native_ads_signal:timeout", 1000, 1000);
    public static final zzbce zzho = new zzbby(2, "DISABLE_CRASH_REPORTING", false, false);
    public static final zzbce zzhp = new zzbby(1, "gads:unsampled_crash_reporting:enabled", false, false);
    public static final zzbce zzhq = new zzbby(1, "gads:simple_promise_exception_reporting:enabled", false, false);
    public static final zzbce zzhr = new zzbby(1, "gads:sample_javascript_engine_exceptions:enabled", false, false);
    public static final zzbce zzhs = new zzbby(1, "gads:sample_webview_initialization_failed_exceptions:enabled", false, false);
    public static final zzbce zzht = new zzbby(1, "gads:exception_with_additional_slices:enabled", false, false);
    public static final zzbce zzhu = new zzbby(1, "gads:exception_with_memory_info:enabled", false, false);
    public static final zzbce zzhv = new zzbby(1, "gads:exception_with_app_version:enabled", false, false);
    public static final zzbce zzhw = new zzbby(1, "gads:use_uri_to_construct_url:enabled", false, false);
    public static final zzbce zzhx = new zzbby(1, "gads:paid_event_listener:enabled", true, true);
    public static final zzbce zzhy = new zzbby(1, "gads:interscroller_ad:enabled", true, true);
    public static final zzbce zzhz = new zzbby(1, "gads:interscroller_ad:refresh:enabled", false, false);
    public static final zzbce zzi = zzbce.zzg(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE, Integer.MAX_VALUE);
    public static final zzbce zziA = new zzbcc(1, "gads:inspector:ui_url", "https://admob-gmats.uc.r.appspot.com/", "https://admob-gmats.uc.r.appspot.com/");
    public static final zzbce zziB = zzbce.zzg(1, "gads:inspector:max_ad_life_cycles", 1000, 1000);
    public static final zzbce zziC = zzbce.zzg(1, "gads:inspector:ui_invocation_millis", 2000, 2000);
    public static final zzbce zziD = new zzbby(1, "gads:inspector:shake_enabled", true, true);
    public static final zzbce zziE = zzbce.zzf(1, "gads:inspector:shake_strength", 2.0f, 2.0f);
    public static final zzbce zziF = zzbce.zzg(1, "gads:inspector:shake_interval", ServiceStarter.ERROR_UNKNOWN, ServiceStarter.ERROR_UNKNOWN);
    public static final zzbce zziG = zzbce.zzg(1, "gads:inspector:shake_reset_time_ms", PathInterpolatorCompat.MAX_NUM_POINTS, PathInterpolatorCompat.MAX_NUM_POINTS);
    public static final zzbce zziH = zzbce.zzg(1, "gads:inspector:shake_count", 3, 3);
    public static final zzbce zziI = new zzbby(1, "gads:inspector:flick_enabled", true, true);
    public static final zzbce zziJ = zzbce.zzf(1, "gads:inspector:flick_rotation_threshold", 45.0f, 45.0f);
    public static final zzbce zziK = zzbce.zzg(1, "gads:inspector:flick_reset_time_ms", PathInterpolatorCompat.MAX_NUM_POINTS, PathInterpolatorCompat.MAX_NUM_POINTS);
    public static final zzbce zziL = zzbce.zzg(1, "gads:inspector:flick_count", 2, 2);
    public static final zzbce zziM = zzbce.zzg(1, "gads:inspector:icon_width_px", 256, 256);
    public static final zzbce zziN = zzbce.zzg(1, "gads:inspector:icon_height_px", 256, 256);
    public static final zzbce zziO = new zzbby(1, "gads:inspector:ad_manager_enabled", true, true);
    public static final zzbce zziP = new zzbby(1, "gads:inspector:server_data_enabled", true, true);
    public static final zzbce zziQ = new zzbby(1, "gads:inspector:bidding_data_enabled", true, true);
    public static final zzbce zziR = new zzbby(1, "gads:inspector:credentials_enabled", true, true);
    public static final zzbce zziS = new zzbby(1, "gads:inspector:export_request_logs_enabled", true, true);
    public static final zzbce zziT = new zzbby(1, "gads:inspector:export_response_logs_enabled", true, true);
    public static final zzbce zziU = zzbce.zzh(1, "gads:inspector:max_ad_response_logs_bytes", 20971520, 20971520);
    public static final zzbce zziV = new zzbby(1, "gads:inspector:sdk_version_enabled", true, true);
    public static final zzbce zziW = new zzbby(1, "gads:inspector:adapter_supports_init_enabled", true, true);
    public static final zzbce zziX = new zzbby(1, "gads:inspector:out_of_context_testing_enabled", true, true);
    public static final zzbce zziY = new zzbby(1, "gads:inspector:out_of_context_testing_v2_enabled", true, true);
    public static final zzbce zziZ = new zzbby(1, "gads:inspector:plugin_enabled", true, true);
    public static final zzbce zzia = new zzbby(1, "gads:offline_ads_notification:enabled", true, true);
    public static final zzbce zzib = new zzbby(1, "gads:use_new_network_api:enabled", true, true);
    public static final zzbce zzic = new zzbby(1, "gads:request_notifications_permission:enabled", false, false);
    public static final zzbce zzid = new zzbby(1, "gads:redirect_users_to_notifications_settings:enabled", false, false);
    public static final zzbce zzie = new zzbby(1, "gads:skip_opt_in_dialog:enabled", true, true);
    public static final zzbce zzif = zzbce.zzg(1, "gads:notification_priority:level", 0, 0);
    public static final zzbce zzig = zzbce.zzg(1, "gads:notification_importance:level", 3, 3);
    public static final zzbce zzih = new zzbby(1, "gads:show_native_ad_assets_in_offline_notification:enabled", true, true);
    public static final zzbce zzii = new zzbby(1, "gads:skip_offline_notification_flow:enabled", false, false);
    public static final zzbce zzij = new zzbby(1, "gads:handle_click_recorded_event:enabled", true, true);
    public static final zzbce zzik = new zzbby(1, "gads:default_network_type_fine_to_unknown:enabled", true, true);
    public static final zzbce zzil = new zzbby(1, "gads:handle_intent_async:enabled", true, true);
    public static final zzbce zzim = new zzbby(1, "gads:skip_deep_link_validation_native_ads:enabled", true, true);
    public static final zzbce zzin = new zzbby(1, "gads:try_deep_link_fallback_native_ads:enabled", true, true);
    public static final zzbce zzio = new zzbby(1, "gads:in_app_link_handling_for_android_11_enabled:enabled", true, true);
    public static final zzbce zzip = new zzbcc(1, "gads:remote_capture_service_url", "https://pagead2.googlesyndication.com/pagead/ping?e=2&f=1", "https://pagead2.googlesyndication.com/pagead/ping?e=2&f=1");
    public static final zzbce zziq = zzbce.zzg(1, "gads:cui_monitoring_interval_ms", 300000, 300000);
    public static final zzbce zzir = zzbce.zzg(1, "gads:cui_buffer_size", 1000, 1000);
    public static final zzbce zzis = zzbce.zzg(1, "gads:cuj_automatic_flush_delay_ms", 30000, 30000);
    public static final zzbce zzit = new zzbcc(1, "gads:plugin_regex", "^Flutter-GMA-.*|^unity-.*", "^Flutter-GMA-.*|^unity-.*");
    public static final zzbce zziu = new zzbby(1, "gads:cui_monitoring_exception_enabled", true, true);
    public static final zzbce zziv = new zzbby(1, "gads:include_experiment_ids_in_cui_pings", true, true);
    public static final zzbce zziw = zzbce.zzg(1, "gads:app_event_queue_size", 20, 20);
    public static final zzbce zzix = new zzbby(1, "gads:hide_grey_title_bar:enabled", false, false);
    public static final zzbce zziy = new zzbby(1, "gads:interstitial_ad_parameter_handler:enabled", true, true);
    public static final zzbce zziz = new zzbby(1, "gads:inspector:enabled", true, true);
    public static final zzbce zzj = zzbce.zzg(1, "gads:video_exo_player_socket_receive_buffer_size", 0, 0);
    public static final zzbce zzjA = zzbce.zzg(1, "gads:paw_cache_refresh_interval_secs", 30, 30);
    public static final zzbce zzjB = zzbce.zzg(1, "gads:paw_cache_retry_delay_secs", 10, 10);
    public static final zzbce zzjC = new zzbby(1, "gads:h5ads:enabled", true, true);
    public static final zzbce zzjD = zzbce.zzg(1, "gads:h5ads:max_num_ad_objects", 10, 10);
    public static final zzbce zzjE = zzbce.zzg(1, "gads:h5ads:max_gmsg_length", 5000, 5000);
    public static final zzbce zzjF = new zzbcc(1, "gads:h5ads:afma_prefix", "(window.AFMA_ReceiveMessage||function(msg,params){window.h5_iframe.contentWindow.postMessage({messageName:'receive_message_action',parameters:{messageName:msg,parameters:params}},'*');})", "(window.AFMA_ReceiveMessage||function(msg,params){window.h5_iframe.contentWindow.postMessage({messageName:'receive_message_action',parameters:{messageName:msg,parameters:params}},'*');})");
    public static final zzbce zzjG = new zzbby(1, "gads:native_html_video_asset:enabled", true, true);
    public static final zzbce zzjH = new zzbby(1, "gads:native_html_image_asset:enabled", true, true);
    public static final zzbce zzjI = new zzbby(1, "gads:rubidium_attribution_reporting:enabled", true, true);
    public static final zzbce zzjJ = new zzbby(1, "gads:open_system_browser_with_ara_param:enabled", true, true);
    public static final zzbce zzjK = zzbce.zzg(1, "gads:minimum_ara_api_granular_version", 233012000, 233012000);
    public static final zzbce zzjL = new zzbby(1, "gads:attribution_reporting_android_s:enabled", false, false);
    public static final zzbce zzjM = new zzbby(1, "gads:ara_for_native_js_executor:enabled", false, false);
    public static final zzbce zzjN = new zzbby(1, "gads:ara_for_native_video:enabled", false, false);
    public static final zzbce zzjO = new zzbby(1, "gads:ara_for_native_image:enabled", false, false);
    public static final zzbce zzjP = new zzbcc(1, "gads:attr_reporting_supported", "ase=3", "ase=3");
    public static final zzbce zzjQ = new zzbcc(1, "gads:attr_reporting_debug_key", "uk", "uk");
    public static final zzbce zzjR = new zzbcc(1, "gads:attr_reporting_nis", "nis", "nis");
    public static final zzbce zzjS = new zzbcc(1, "gads:attr_reporting_source_registered_platform", "asr", "asr");
    public static final zzbce zzjT = new zzbcc(1, "gads:attr_reporting_domain_overwrite", "asrd=1", "asrd=1");
    public static final zzbce zzjU = new zzbcc(1, "gads:attr_reporting_redirect_url", "www.googleadservices.com", "www.googleadservices.com");
    public static final zzbce zzjV = zzbce.zzg(1, "gads:attr_reporting_timeout_duration_millis", 1000, 1000);
    public static final zzbce zzjW = new zzbby(1, "gads:ara_unsampled_crash_reporting:enabled", false, false);
    public static final zzbce zzjX = new zzbby(1, "gads:topics_app_allowlist:enabled", true, true);
    public static final zzbce zzjY = new zzbcc(1, "gads:topics_app_allowlist_comma_separated", "", "");
    public static final zzbce zzjZ = zzbce.zzg(1, "gads:minimum_topics_api_granular_version", 233012000, 233012000);
    public static final zzbce zzja = new zzbby(1, "gads:inspector:ad_transaction_extras_enabled", true, true);
    public static final zzbce zzjb = new zzbby(1, "gads:inspector:ui_storage_enabled", true, true);
    public static final zzbce zzjc = new zzbcc(1, "gads:inspector:user_shared_preference_keys_csv", "IABTCF_AddtlConsent,IABTCF_gdprApplies,IABTCF_TCString", "IABTCF_AddtlConsent,IABTCF_gdprApplies,IABTCF_TCString");
    public static final zzbce zzjd = new zzbcc(1, "gads:inspector:gma_shared_preference_keys_csv", "", "");
    public static final zzbce zzje = new zzbby(1, "gads:ad_shield_version_csi:enabled", false, false);
    public static final zzbce zzjf = new zzbby(1, "gads:paw_register_webview:enabled", true, true);
    public static final zzbce zzjg = new zzbby(1, "gads:paw_webview_early_initialization:enabled", true, true);
    public static final zzbce zzjh = zzbce.zzg(1, "gads:max_timeout_view_click_ms", 1000, 1000);
    public static final zzbce zzji = new zzbby(1, "gads:as_view_click_latency_logging:enabled", false, false);
    public static final zzbce zzjj = new zzbby(2, "DISABLE_EARLY_INITIALIZATION", false, false);
    public static final zzbce zzjk = new zzbby(1, "gads:third_party_cookie_status_for_paw:enabled", true, true);
    public static final zzbce zzjl = new zzbby(1, "gads:csi_on_orions_belt_for_paw:enabled", false, false);
    public static final zzbce zzjm = new zzbby(1, "gads:recording_click_for_paw:enabled", true, true);
    public static final zzbce zzjn = new zzbby(1, "gads:init_sdk_once_for_paw:enabled", false, false);
    public static final zzbce zzjo = zzbce.zzg(1, "gads:max_init_sdk_retries_for_paw:enabled", 0, 0);
    public static final zzbce zzjp = new zzbby(1, "gads:num_registered_web_views_param:enabled", true, true);
    public static final zzbce zzjq = zzbce.zzg(1, "gads:paw_delegate_web_view_client_refresh_interval_ms", 60000, 60000);
    public static final zzbce zzjr = new zzbcc(1, "gads:paw_app_signals_javascript", "window.gmaSdk.as=%1$s", "window.gmaSdk.as=%1$s");
    public static final zzbce zzjs = new zzbcc(1, "gads:paw_signals_eid_allowlist", "", "");
    public static final zzbce zzjt = new zzbby(1, "gads:pact_enabled:enabled", true, true);
    public static final zzbce zzju = zzbce.zzg(1, "gads:pact_polling_duration_ms", 60000, 60000);
    public static final zzbce zzjv = new zzbby(1, "gads:pact_polling_forever:enabled", false, false);
    public static final zzbce zzjw = zzbce.zzh(1, "gads:pact_polling_interval_ms", 100, 100);
    public static final zzbce zzjx = new zzbcc(1, "gads:pact_navigation_event_to_request_channel", DiskLruCache.VERSION, DiskLruCache.VERSION);
    public static final zzbce zzjy = new zzbcc(1, "gads:pact_active_exp_id:enabled", HttpUrl.PATH_SEGMENT_ENCODE_SET_URI, HttpUrl.PATH_SEGMENT_ENCODE_SET_URI);
    public static final zzbce zzjz = zzbce.zzh(1, "gads:paw_cache_ttl_ms", 60000, 60000);
    public static final zzbce zzk = zzbce.zzg(1, "gads:video_exo_player:min_retry_count", -1, -1);
    public static final zzbce zzkA = new zzbby(1, "gads:appstate_getresource_fix:enabled", true, true);
    public static final zzbce zzkB = new zzbby(1, "gads:convert_ad_unit_lower_case_rtb:enabled", false, false);
    public static final zzbce zzkC = new zzbby(1, "gads:drx_ad_unit_regex_case_insensitive:enabled", false, false);
    public static final zzbce zzkD = new zzbby(1, "gads:csi_ping_for_invalid_dynamite_flags_access:enabled", false, false);
    public static final zzbce zzkE = new zzbby(1, "gads:gestures:paos:enabled", true, true);
    public static final zzbce zzkF = new zzbby(1, "gads:normalized_device_volume:enabled", false, false);
    public static final zzbce zzkG = new zzbby(1, "gads:register_receiver_options:enabled", true, true);
    public static final zzbce zzkH = new zzbby(1, "gads:catching_security_exception_on_intent:enabled", true, true);
    public static final zzbce zzkI = new zzbby(1, "gads:drop_is_sidewinder:enabled", true, true);
    public static final zzbce zzkJ = new zzbby(1, "gads:explicit_intent_on_download:enabled", true, true);
    public static final zzbce zzkK = new zzbby(1, "gads:queryInfo_generate_bg:enabled", false, false);
    public static final zzbce zzkL = new zzbby(1, "gads:bg_banner_resume:enabled", false, false);
    public static final zzbce zzkM = new zzbby(1, "gads:bg_banner_destroy:enabled", false, false);
    public static final zzbce zzkN = new zzbby(1, "gads:bg_banner_pause:enabled", false, false);
    public static final zzbce zzkO = new zzbby(2, "OPTIMIZE_INITIALIZATION", false, false);
    public static final zzbce zzkP = new zzbby(2, "OPTIMIZE_AD_LOADING", false, false);
    public static final zzbce zzkQ = zzbce.zzg(1, "gads:v46_granular_version", 221080000, 221080000);
    public static final zzbce zzkR = zzbce.zzg(1, "gads:v48_granular_version", 221909000, 221909000);
    public static final zzbce zzkS = new zzbby(1, "gads:manifest_flag_collection:enabled", false, false);
    public static final zzbce zzkT = new zzbby(1, "gads:remove_ua_lock:enabled", true, true);
    public static final zzbce zzkU = new zzbby(1, "gads:fixed_size_bg_thread_pool:enabled", false, false);
    public static final zzbce zzkV = zzbce.zzg(1, "gads:core_bg_thread_pool_size", 8, 8);
    public static final zzbce zzkW = new zzbby(1, "gads:allow_core_thread_timeout:enabled", true, true);
    public static final zzbce zzkX = new zzbby(1, "gads:bstar_csi:enabled", true, true);
    public static final zzbce zzkY = new zzbby(1, "gads:bstar_signals:enabled", true, true);
    public static final zzbce zzkZ = new zzbby(1, "gads:bstar_display_count_signal:enabled", false, false);
    public static final zzbce zzka = zzbce.zzg(1, "gads:minimum_topics_api_android_version", 33, 33);
    public static final zzbce zzkb = new zzbby(1, "gads:topics_signal:enabled", false, false);
    public static final zzbce zzkc = new zzbby(1, "gads:topics_unsampled_exception_reporting:enabled", false, false);
    public static final zzbce zzkd = zzbce.zzg(1, "gads:topics_signal_timeout_duration_in_ms", ServiceStarter.ERROR_UNKNOWN, ServiceStarter.ERROR_UNKNOWN);
    public static final zzbce zzke = zzbce.zzh(1, "gads:topics_api_consent_in_millis", TimeUnit.DAYS.toMillis(1), TimeUnit.DAYS.toMillis(1));
    public static final zzbce zzkf = new zzbby(1, "gads:ppt_check_for_topics_signal", true, true);
    public static final zzbce zzkg = new zzbcc(1, "gads:topics_consent:shared_preference_key_list", "{  \"__default__\": [    \"IABTCF_TCString\",    \"gad_has_consent_for_cookies\",    \"gad_rdp\",    \"personalized_ad_status\",    \"IABUSPrivacy_String\",    \"UPTC_UptcString\",  ]}", "{  \"__default__\": [    \"IABTCF_TCString\",    \"gad_has_consent_for_cookies\",    \"gad_rdp\",    \"personalized_ad_status\",    \"IABUSPrivacy_String\",    \"UPTC_UptcString\",  ]}");
    public static final zzbce zzkh = new zzbcc(1, "gads:csi_log_consent:shared_preference_key_list", "", "");
    public static final zzbce zzki = new zzbcc(1, "gads:gen204_log_consent:shared_preference_key_list", "", "");
    public static final zzbce zzkj = new zzbby(1, "gads:msa:alphavis_enabled", false, false);
    public static final zzbce zzkk = new zzbby(1, "gads:msa:adutilalphavis_enabled", false, false);
    public static final zzbce zzkl = new zzbby(1, "gads:msa:nativealphavis_enabled", false, false);
    public static final zzbce zzkm = zzbce.zzg(1, "gads:msa:visminalpha", 0, 0);
    public static final zzbce zzkn = new zzbby(1, "gads:msa:vswfl", true, true);
    public static final zzbce zzko = new zzbby(1, "gads:msa:poslogger", false, false);
    public static final zzbce zzkp = new zzbby(1, "gads:new_dynamite_module_method:enabled", false, false);
    public static final zzbce zzkq = zzbce.zzg(1, "gads:timeout_for_show_call_succeed:ms", PathInterpolatorCompat.MAX_NUM_POINTS, PathInterpolatorCompat.MAX_NUM_POINTS);
    public static final zzbce zzkr = new zzbby(1, "gads:read_pub_callback_param_open_gmsg:enabled", true, true);
    public static final zzbce zzks = new zzbby(1, "gads:read_pub_callback_param_click_gmsg:enabled", true, true);
    public static final zzbce zzkt = new zzbby(1, "gads:forward_physical_click_to_ad_listener:enabled", true, true);
    public static final zzbce zzku = new zzbby(1, "gads:webview_destroy_workaround:enabled", true, true);
    public static final zzbce zzkv = new zzbby(1, "gads:evaluate_js_on_ui_thread:enabled", false, false);
    public static final zzbce zzkw = new zzbby(1, "gads:mraid_collapse_on_ui_thread:enabled", true, true);
    public static final zzbce zzkx = new zzbby(1, "gads:mraid_collapse_remove_view_before_dismiss:enabled", false, false);
    public static final zzbce zzky = new zzbby(1, "gads:mraid_collapse_remove_parent:enabled", false, false);
    public static final zzbce zzkz = new zzbby(1, "gads:mraid_collapse_catch_exception:enabled", false, false);
    public static final zzbce zzl = new zzbby(1, "gads:video_exo_player:fmp4_extractor_enabled", true, true);
    public static final zzbce zzlA = new zzbby(1, "gads:populate_additional_native_ad_options:enabled", true, true);
    public static final zzbce zzlB = new zzbby(1, "gads:migrate_call_from_schedule_at_fixed_rate:enabled", false, false);
    public static final zzbce zzlC = new zzbby(1, "gads:in_ad_unit:enabled", true, true);
    public static final zzbce zzlD = new zzbby(1, "gads:lock_screen_webviews:enabled", true, true);
    public static final zzbce zzlE = new zzbby(1, "gads:skip_mobius_signal:enabled", false, false);
    public static final zzbce zzlF = new zzbby(1, "gads:skip_constants_signal:enabled", false, false);
    public static final zzbce zzlG = new zzbby(1, "gads:msa:cxyun:enabled", false, false);
    public static final zzbce zzlH = new zzbby(1, "gads:csi_for_delayed_banner:enabled", false, false);
    public static final zzbce zzlI = new zzbby(1, "gads:use_local_ad_shield_utils:enabled", false, false);
    public static final zzbce zzlJ = new zzbby(1, "gads:maybe_use_new_api_for_battery_signal:enabled", false, false);
    public static final zzbce zzlK = zzbce.zzg(1, "gads:telephony_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlL = zzbce.zzg(1, "gads:static_device_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlM = zzbce.zzg(1, "gads:shared_pref_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlN = zzbce.zzg(1, "gads:sdk_environment_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlO = zzbce.zzg(1, "gads:scion_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlP = zzbce.zzg(1, "gads:per_app_id_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlQ = zzbce.zzg(1, "gads:app_permissions_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlR = zzbce.zzg(1, "gads:omid_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlS = zzbce.zzg(1, "gads:memory_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlT = zzbce.zzg(1, "gads:inspector_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlU = zzbce.zzg(1, "gads:debug_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlV = zzbce.zzg(1, "gads:consent_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlW = zzbce.zzg(1, "gads:cache_key_generation_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlX = zzbce.zzg(1, "gads:battery_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlY = zzbce.zzg(1, "gads:audio_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzlZ = zzbce.zzg(1, "gads:attribution_reporting_supported_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzla = new zzbby(1, "gads:bstar_display_count_impression_url_param:enabled", false, false);
    public static final zzbce zzlb = new zzbby(1, "gads:emulator:ranchu_check_enabled", true, true);
    public static final zzbce zzlc = new zzbby(1, "gads:unity_signals:enabled", true, true);
    public static final zzbce zzld = new zzbby(1, "gads:unity_view_spam_signals:enabled", true, true);
    public static final zzbce zzle = new zzbby(1, "gads:full_screen_1px_open:enabled", true, true);
    public static final zzbce zzlf = new zzbby(1, "gads:app_id_as_session_token:enabled", false, false);
    public static final zzbce zzlg = new zzbby(1, "gads:lmd_overlay_v56_plus:enabled", false, false);
    public static final zzbce zzlh = new zzbby(1, "gads:custom_click_gesture_v2:enabled", true, true);
    public static final zzbce zzli = new zzbby(1, "gads:ads_service:enabled", false, false);
    public static final zzbce zzlj = zzbce.zzh(1, "gads:service_signal_timeout:millis", 60000, 60000);
    public static final zzbce zzlk = zzbce.zzh(1, "gads:service_proxy_timeout:millis", 60000, 60000);
    public static final zzbce zzll = new zzbby(1, "gads:iltv_adloader_banner:enabled", true, true);
    public static final zzbce zzlm = new zzbby(1, "gads:mixed_content_never_allow:enabled", false, false);
    public static final zzbce zzln = new zzbby(1, "gads:csi_ping_for_paid_event_callback:enabled", false, false);
    public static final zzbce zzlo = new zzbby(1, "gads:adapter_versions_in_every_ad_request:enabled", true, true);
    public static final zzbce zzlp = new zzbby(1, "gads:app_settings_expiry_check_on_init:enabled", false, false);
    public static final zzbce zzlq = new zzbby(1, "gads:app_settings_expiry_check_in_getter:enabled", false, false);
    public static final zzbce zzlr = new zzbby(1, "gads:use_server_defined_cld_ttl:enabled", false, false);
    public static final zzbce zzls = zzbce.zzh(1, "gads:sdk_defined_cld_ttl_secs", -1, -1);
    public static final zzbce zzlt = new zzbcc(1, "gads:disabled_signals_list", "", "");
    public static final zzbce zzlu = new zzbcc(1, "gads:cached_signals_list", "", "");
    public static final zzbce zzlv = new zzbby(1, "gads:auto_refresh_cached_signals:enabled", false, false);
    public static final zzbce zzlw = new zzbby(1, "gads:caching_signals_source_refactor:enabled", false, false);
    public static final zzbce zzlx = new zzbby(1, "gads:use_stale_cached_signals:enabled", false, false);
    public static final zzbce zzly = new zzbby(1, "gads:csi_for_stale_cached_signals:enabled", false, false);
    public static final zzbce zzlz = new zzbby(1, "gads:use_app_open_ad_for_cld:enabled", true, true);
    public static final zzbce zzm = new zzbby(1, "gads:video_exo_player:treat_load_exception_as_non_fatal", true, true);
    public static final zzbce zzmA = new zzbby(1, "gads:enable_afai_signal", false, false);
    public static final zzbce zzmB = new zzbby(1, "gads:enable_compose_csi_logging", false, false);
    public static final zzbce zzmC = new zzbby(1, "gads:ad_overlay_info_parcel_memory_leak_fix", false, false);
    public static final zzbce zzmD = new zzbby(1, "gads:remote_service_memory_leak_fix", false, false);
    public static final zzbce zzmE = zzbce.zzg(1, "gads:ad_overlay_objects_map_retain_duration_seconds", 60, 60);
    public static final zzbce zzmF = new zzbby(1, "gads:immersive_video_ads:enabled", true, true);
    public static final zzbce zzmG = new zzbby(1, "gads:add_exception_to_failed_adapter_init_cui:enabled", false, false);
    public static final zzbce zzmH = new zzbby(1, "gads:enable_log_scion_event_gmsg_for_native_js:enabled", false, false);
    public static final zzbce zzmI = new zzbby(1, "gads:should_sample_fetch_rtb_info_exception:enabled", false, false);
    private static final Integer zzmJ;
    public static final zzbce zzma = zzbce.zzg(1, "gads:ad_size_parcel_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzmb = zzbce.zzg(1, "gads:ad_response_key_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzmc = zzbce.zzg(1, "gads:adapter_versions_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzmd = zzbce.zzg(1, "gads:cld_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzme = zzbce.zzg(1, "gads:ad_key_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzmf = zzbce.zzg(1, "gads:hardware_acceleration_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzmg = zzbce.zzg(1, "gads:ad_shield_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzmh = zzbce.zzg(1, "gads:gbid_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzmi = zzbce.zzg(1, "gads:mobius_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzmj = zzbce.zzg(1, "gads:banner_refresh_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzmk = zzbce.zzg(1, "gads:afai_signal_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzml = new zzbby(1, "gads:mute_webview_audio_when_paused:enabled", false, false);
    public static final zzbce zzmm = new zzbby(1, "gads:pause_resume_banner_webview_on_visibility_change", false, false);
    public static final zzbce zzmn = new zzbby(1, "gads:log_webview_audio_mute_supported:enabled", false, false);
    public static final zzbce zzmo = new zzbby(1, "gads:log_webview_pause_resume_exceptions:enabled", false, false);
    public static final zzbce zzmp = new zzbby(1, "gads:csi_for_initialization_latency_metrics:enabled", false, false);
    public static final zzbce zzmq = new zzbby(1, "gads:maybe_invoke_remove_view_call_in_close_overlay", false, false);
    public static final zzbce zzmr = zzbce.zzg(1, "gads:video_metric_reporting_sample_rate", 5, 5);
    public static final zzbce zzms = zzbce.zzg(1, "gads:exception_reporting_sample_rate", 5, 5);
    public static final zzbce zzmt = new zzbby(1, "gads:read_ignore_click_action_param_open_gmsg:enabled", false, false);
    public static final zzbce zzmu = new zzbby(1, "gads:install_source_info_signal:enabled", false, false);
    public static final zzbce zzmv = new zzbby(1, "gads:should_use_new_dice_logic_for_crash_reporting", true, true);
    public static final zzbce zzmw = new zzbby(1, "gads:native_video_get_current_time_fix:enabled", false, false);
    public static final zzbce zzmx = new zzbby(1, "gads:enable_hsdp_migration_signal", true, true);
    public static final zzbce zzmy = zzbce.zzg(1, "gads:hsdp_migration_timeout_duration_in_ms", 5000, 5000);
    public static final zzbce zzmz = zzbce.zzg(1, "gads:sdk_banner_refresh_ad_load_delay_seconds", 30, 30);
    public static final zzbce zzn = new zzbby(1, "gads:video_exo_player:byte_buffer_count_enabled", false, false);
    public static final zzbce zzo = new zzbby(1, "gads:null_key_bundle_to_json:enabled", false, false);
    public static final zzbce zzp = zzbce.zzg(1, "gads:video_stream_cache:limit_count", 5, 5);
    public static final zzbce zzq = zzbce.zzg(1, "gads:video_stream_cache:limit_space", 8388608, 8388608);
    public static final zzbce zzr = zzbce.zzg(1, "gads:video_stream_exo_cache:buffer_size", 8388608, 8388608);
    public static final zzbce zzs = new zzbby(1, "gads:csi:enable_timestamp_preload_apis", false, false);
    public static final zzbce zzt = zzbce.zzh(1, "gads:preload_ad:refill_buffer_time_millis", 100, 100);
    public static final zzbce zzu = zzbce.zzh(1, "gads:preload_ad_default_refresh_interval:millis", 1000, 1000);
    public static final zzbce zzv = zzbce.zzh(1, "gads:preload_ad_default_refresh_max_interval:millis", PeriodicWorkRequest.MIN_PERIODIC_FLEX_MILLIS, PeriodicWorkRequest.MIN_PERIODIC_FLEX_MILLIS);
    public static final zzbce zzw = zzbce.zzg(1, "gads:preload_ad_max_backoff:times", 13, 13);
    public static final zzbce zzx = zzbce.zzh(1, "gads:preload_ad:ttl_sec", 3600, 3600);
    public static final zzbce zzy = zzbce.zzg(1, "gads:preload_app_open_queue_size:upper_bound", 15, 15);
    public static final zzbce zzz = zzbce.zzg(1, "gads:preload_interstitial_queue_size:upper_bound", 15, 15);

    static {
        new zzbcc(1, "gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
        zzbdx zzbdx = zzbet.zza;
        zzbce.zzg(1, "gads:http_url_connection_factory:timeout_millis", 10000, 10000);
        new zzbby(1, "gads:video_exo_player:use_play_back_info_for_should_start_play_back", true, true);
        new zzbby(1, "gads:video_exo_player:wait_with_timeout", true, true);
        zzbce.zzg(1, "gads:video_exo_player:wait_timeout_ms", ServiceStarter.ERROR_UNKNOWN, ServiceStarter.ERROR_UNKNOWN);
        zzbce.zzh(1, "gads:sai:server_side_npa:ttl", TimeUnit.DAYS.toMillis(90), TimeUnit.DAYS.toMillis(90));
        new zzbby(1, "gads:tfcd_deny_ad_storage:enabled", true, true);
        new zzbby(1, "gads:tfua_deny_ad_storage:enabled", true, true);
        new zzbby(1, "gads:new_rewarded_ad:enabled", true, true);
        new zzbby(1, "gads:gen204_signals:enabled", false, false);
        new zzbby(1, "gads:msa:experiments:enabled", false, false);
        zzbce.zzg(1, "gads:gestures:a2:enabled", 0, 0);
        zzbce.zzg(1, "gads:msa:gct:to", 5000, 5000);
        new zzbby(1, "gads:gestures:brt:enabled", true, true);
        new zzbby(1, "gads:signal:clear_paid_v1_for_3p:enabled", false, false);
        new zzbcc(1, "gads:gestures:pk", "", "");
        new zzbby(1, "gads:gestures:bs:enabled", true, true);
        zzbce.zzg(1, "gads:gestures:as2percentage", 0, 0);
        zzbce.zzi(1, "gads:sdk_core_constants:experiment_id");
        new zzbby(1, "gads:js_flags:disable_phenotype", false, false);
        zzbce.zzg(1, "gads:cache:ad_request_timeout_millis", ItemTouchHelper.Callback.DEFAULT_SWIPE_ANIMATION_DURATION, ItemTouchHelper.Callback.DEFAULT_SWIPE_ANIMATION_DURATION);
        zzbce.zzg(1, "gads:cache:max_concurrent_downloads", 10, 10);
        new zzbby(1, "gads:cache:downloader_use_high_priority", false, false);
        zzbce.zzh(1, "gads:cache:javascript_timeout_millis", CoroutineLiveDataKt.DEFAULT_TIMEOUT, CoroutineLiveDataKt.DEFAULT_TIMEOUT);
        new zzbby(1, "gads:cache:function_call_timeout_v1:enabled", false, false);
        zzbce.zzh(1, "gads:cache:function_call_timeout", CoroutineLiveDataKt.DEFAULT_TIMEOUT, CoroutineLiveDataKt.DEFAULT_TIMEOUT);
        new zzbby(1, "gads:cache:add_itag_to_cache_key:enabled", true, true);
        new zzbby(1, "gads:omid_use_admob_impl_dependency:enabled", true, true);
        new zzbby(1, "gads:nonagon:banner:enabled", true, true);
        new zzbcc(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)", "(?!)");
        new zzbby(1, "gads:nonagon:app_open:enabled", true, true);
        new zzbcc(1, "gads:nonagon:app_open:ad_unit_exclusions", "(?!)", "(?!)");
        new zzbby(1, "gads:nonagon:interstitial:enabled", true, true);
        new zzbcc(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)", "(?!)");
        new zzbby(1, "gads:nonagon:rewardedvideo:enabled", true, true);
        new zzbby(1, "gads:nonagon:mobile_ads_setting_manager:enabled", true, true);
        zzbce.zzg(1, "gads:nonagon:parallel_renderer:count", -1, -1);
        new zzbby(1, "gads:skip_init_for_app_open_ad_request:enabled", false, false);
        new zzbby(1, "gads:signals:doritos:enabled", false, false);
        new zzbby(1, "gads:signals:doritos:v2:immediate:enabled", false, false);
        new zzbby(1, "gads:attestation_token:enabled", false, false);
        new zzbby(1, "gads:query_map_update_bg_thread:enabled", false, false);
        new zzbby(1, "gads:scar_signal_comparison_experiment:enabled", false, false);
        zzbce.zzh(1, "gads:timeout_signal_collection_in_exp:millis", 1000, 1000);
        new zzbby(1, "gads:scar_decrypt_csi_for_gbid:enabled", false, false);
        Integer num = 808;
        zzmJ = num;
        num.intValue();
        num.intValue();
        new zzbby(1, "gads:leibniz:events:enabled", false, false);
        new zzbby(1, "gads:lmd_overlay:enabled", true, true);
    }

    public static void zza(Context context) {
        zzbcp.zza(new zzbcm(context));
    }
}
